apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
type: Opaque
stringData:
  config.yaml: |
    telegram_token: "<TOKEN>"
    template_path: "/etc/telegrambot/template.tmpl"
    time_zone: "Europe/Moscow"
    split_token: "|"
    time_outdata: "02/01/2006 15:04:05"
    split_msg_byte: 1000
    send_only: true
  template.tmpl: |
    Type: {{.CommonAnnotations.description}}
    Summary: {{.CommonAnnotations.summary}}
    Alertname: {{ .CommonLabels.alertname }}
    Instance: {{ .CommonLabels.instance }}
    Serverity: {{ .CommonLabels.serverity}}
    Status:  {{ .Status }}