apiVersion: apps/v1
kind: Deployment
metadata:
  name: ges-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ges-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ges-app
    spec:
      containers:
      - name: ges-app
        # image: cr.yandex/crp502n0k1f2a7o9qfi2/ges:0.1.3
        image: dr.senz.su/ges_exporter:0.1.1
        ports:
        - name: web
          containerPort: 80
      imagePullSecrets:
        - name: dr-senz-su