apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    role: alert-rules
    prometheus: prometheus
  name: prometheus-example-rules
spec:
  groups:
  # - name: ./example.rules
  #   rules:
  #   - alert: ExampleAlert
  #     expr: vector(1)
  #     for: 0m
  #     labels:
  #       severity: critical
  #     annotations:
  #       summary: Prometheus AlertManager E2E dead man switch (instance {{ $labels.instance }})
  #       description: "Prometheus DeadManSwitch is an always-firing alert. It's used as an end-to-end test of Prometheus through the Alertmanager.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - name: is_for_sale
    rules:
    - alert: IsForSaleAlert
      expr: is_for_sale > 0
      for: 1m
      annotations:
        summary: Билеееетики на рейв появились! https://v-a-c-special.lastick.ru/events/fe418584-2068-496e-8000-51d5f26beba0?date=2022-01-22&hall=6fc50a3c-5b8b-4be6-af67-afe098bb12af
        